### ISSUE TITLE
issue with plugin

### ISSUE THREAD

**Issue by earthy12333222** [y21/discordcaptcha#39]
internal/modules/cjs/loader.js:964
    throw err;
    ^

SyntaxError: C:\Users\vdavi\Documents\discordcaptcha-master\config.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
?[90m    at Object.Module._extensions..json (internal/modules/cjs/loader.js:961:27)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:790:32)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:703:12)?[39m
?[90m    at Module.require (internal/modules/cjs/loader.js:830:19)?[39m
?[90m    at require (internal/modules/cjs/helpers.js:68:18)?[39m
    at Object.<anonymous> (C:\Users\vdavi\Documents\discordcaptcha-master\client.js:3:16)
?[90m    at Module._compile (internal/modules/cjs/loader.js:936:30)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:790:32)?[39m

C:\Users\vdavi\Documents\discordcaptcha-master>

**Comment by y21** [comment]
Could you please send the contents of your config file? Without the token, of course. I'm assuming the JSON file is blank? 
Alternatively, you could paste the contents of that file on a JSON Validator like [this one](https://jsonformatter.curiousconcept.com/) to see where the syntax error is.

**Comment by earthy12333222** [comment]
I got a new error

**Comment by earthy12333222** [comment]
C:\Users\vdavi\Documents\discordcaptcha-master\events\message.js:3
    if (this.config.ignoreServers.includes((message.guild || { id: "0" }).id)) return;
                                  ^

TypeError: Cannot read property 'includes' of undefined
    at Client.module.exports.run (C:\Users\vdavi\Documents\discordcaptcha-master\events\message.js:3:35)
    at Client.emit (events.js:209:13)
    at MessageCreateHandler.handle (C:\Users\vdavi\Documents\discordcaptcha-master\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\vdavi\Documents\discordcaptcha-master\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (C:\Users\vdavi\Documents\discordcaptcha-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\Users\vdavi\Documents\discordcaptcha-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (C:\Users\vdavi\Documents\discordcaptcha-master\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:209:13)
    at Receiver.receiverOnMessage (C:\Users\vdavi\Documents\discordcaptcha-master\node_modules\ws\lib\websocket.js:789:20)
    at Receiver.emit (events.js:209:13)

**Comment by y21** [comment]
That would be because the key `ignoreServers` does not exist in your config file. Again, can you please send the config file with your token being censored out? That would make it a lot easier.

**Comment by y21** [comment]
@earthy12333222 Are you still having that problem or can I close this issue?
